### ISSUE TITLE
Sometimes the exporter may hang on /metrics indefinitly

### ISSUE THREAD

**Issue by sereinity** [hipages/php-fpm_exporter#253]
Hello,

First thank you for this great software that help us monitor our stacks.

## Summary

Sometimes fpm-exporter doesn't work well and hang when queriying `/metrics` appearing as an unhealthy target in prometheus.

## Context

We use the exporter as a sidecar on a kubernetes engine.
We have 16 fpm-exporter per environment with the exact same configuration. But some (one or two) of them doesn't behave correctly:

## Symptoms

When we query the exporter on the root (`curl localhost:9253/`) they responds that the metrics lives in `/metrics` but when querying it it never responds; and over time those instances take more and more RAM (linearly, I didn't put memory limits yet).

Killing fpm or fpm-exporter (running `kill 1` in containers) may fix it (I say may because there is still a bigger memory usage that clean instances and it looks like those instances may be more prone to hang again)

Here are CPU and memory graphs of a clean instance
![image](https://user-images.githubusercontent.com/2931543/189099308-34c8daf2-7d4d-4bfb-be00-619a71f4539d.png)
![image](https://user-images.githubusercontent.com/2931543/189099346-1f11daff-6fa1-4869-92b7-64a6fe522ff6.png)

Here are CPU and memory graphs of an unhealty instance
![image](https://user-images.githubusercontent.com/2931543/189099590-e9d23c2b-2768-49a4-b332-13ba28905262.png)
![image](https://user-images.githubusercontent.com/2931543/189149528-5f4c0119-3c80-4895-a103-cc1a8a556c53.png)

Timeline:
  - We can see the killing of the php-fpm at 9:52
  - 40 minutes later at 10:29, this exact instance stop working again, all 15 others no problems
  - then I killed fpm at 10:55 which also restored it
  -  … until 11:34 (again ~40minutes, andstill no problem on other fpm-exporters)
  - then I killed both fpm and fpm-exporter at 12:06 (this time it did re-create the container inside the pod, and took <10Mb)
  - break again at 12:08
  - restart fpm at 12:25 (I planed to stop here, but as this time the memory usage were low I decided to try one last time :woman_shrugging: )
  - worked until 13:23

Note: there is absolutely no relevant logs, only `connection refused` when restarting fpm. (I plan to test with more verbosity).

## Conf sample

```yaml
---
kind: Deployment
# …
spec:
  template:
    spec:
      containers:
        - name: fpm
          # …
        - name: fpm-exporter
           env:
             - name: PHP_FPM_SCRAPE_URI
               value: tcp://127.0.0.1:9001/status  # 9001 is only used to expose the status
             - name: PHP_FPM_FIX_PROCESS_COUNT
               value: "true"
            image: hipages/php-fpm_exporter:2.2.0
            imagePullPolicy: IfNotPresent
            livenessProbe:
              httpGet:
                path: /
                port: fpm-metrics
                scheme: HTTP
            ports:
            - containerPort: 9253
              name: fpm-metrics
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /
                port: fpm-metrics
                scheme: HTTP
```

## What can I do?

We can see that healthy instances takes less than 10Mb of memory, but even after a restart, the previously unhealthy instance still takes 60Mb; I would love to put a memory limit, but I unsure about setting it on something like 32Mb.

I could also put the liveness on `/metrics` but unsure if it's a good idea.

Ready to read your propositions folks :slightly_smiling_face:
