### ISSUE TITLE
Using http protocol instead of tcp

### ISSUE THREAD

**Issue by erfansahaf** [hipages/php-fpm_exporter#97]
First of all, thanks for your time and for developing this exporter for the open-source community.

I wish to use `php-fpm_exporter` alongside my `application` container by a docker-compose file. My PHP pool status is accessible by `http://application/status` page, but the exporter can not pull the metrics from this endpoint. The request to the mentioned endpoint will be proxied by Nginx to the fastcgi `127.0.0.1:9000`.

```
location ~ ^/(status)$ {
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
    }
```

I guess there is something wrong with the protocol (that in my case is `http`) but your examples are all using `tcp`. When I try to see the exporter container logs, it shows the following error (I tried with the `tcp` protocol but didn't work either and the `phpfpm_up` was still 0) : 
```
$ docker-compose logs php-fpm_exporter   

php-fpm_exporter_1  | time="2020-05-16T19:18:26Z" level=info msg="Starting server on :9253 with path /metrics"
php-fpm_exporter_1  | time="2020-05-16T19:18:31Z" level=error msg="dial http: unknown network http"
php-fpm_exporter_1  | time="2020-05-16T19:18:31Z" level=error msg="dial http: unknown network http"
php-fpm_exporter_1  | time="2020-05-16T19:18:31Z" level=debug msg="Updated 1 pool(s) in 7.307171ms"
php-fpm_exporter_1  | time="2020-05-16T19:18:31Z" level=error msg="Error scraping PHP-FPM: dial http: unknown network http"
```

My docker-compose.yml file:
```
  application:
   image: my-application:latest
    ports:
      - 3000:80

  php-fpm_exporter:
    image: hipages/php-fpm_exporter
    depends_on:
      - application
    environment:
      - PHP_FPM_SCRAPE_URI=http://application:80/status
      - PHP_FPM_LOG_LEVEL=debug
    ports:
    - 9253:9253
```
